/*
 * Generated by vite-plugin-collections
 *
*/
declare module "#posts" {
  export type Post = {
    id: string
    body: string
    title: string
    summary?: string
  }

  export function list(): Promise<Post[]>
  export function get(id: string): Promise<Post>
}