import type { Type } from '../src/index'
import { write_definitions } from '../src/typing'
import { delete_file } from '../src/utils'
import fs from 'fs/promises'


test('write_definitions', async () => {
  const path = 'test/fixtures/collections.d.ts'
  const types: Type[] = [
    { name: 'title', type: 'string', optional: false },
    { name: 'summary', type: 'string', optional: true }
  ]

  await delete_file(path)
  await write_definitions(path, types, "posts")

  const data = await fs.readFile(path, 'utf-8')

  expect(data).toEqual(`/*
 * Generated by vite-plugin-collections
 *
*/
declare module "#posts" {
  export type Post = {
    title: string
    summary?: string
  }

  export function list(): Promise<Post[]>
  export function get(id: string): Promise<Post>
}`)
})
